### ISSUE TITLE
Las políticas no están actualizadas

### ISSUE THREAD

**Issue by L3ml** [kleros/kleros-docs#15]
No aparecen las reglas 1.2 dentro del tutorial
https://kleros.gitbook.io/docs/products/proof-of-humanity/proof-of-humanity-tutorial
En la pestaña "Register your profile" aparece la versión 1.1 y más abajo un link que dice "Check de guideline" te lleva a la primera versión.
En la sección "Proof Humanity Tutorial (Remove & Challenge)" dentro de la pestaña "Challenge a profile" aparece la primera versión nuevamente. 
Solamente está actualizado en la página de Kleros cuando hay un challenge.
Gracias

**Comment by jaybuidl** [comment]
Superseded by #22
